### ISSUE TITLE
ModuleNotFoundError: No module named 'gql.transport.exceptions'

### ISSUE THREAD

**Issue by timigod** [edgeee/buycoins-python#6]
This is what happens when I try to import the library:

```
>>> import buycoins as bc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/buycoins/__init__.py", line 3, in <module>
    from .client import initialize
  File "/usr/local/lib/python3.7/site-packages/buycoins/client.py", line 6, in <module>
    from gql.transport.exceptions import TransportQueryError, TransportServerError
ModuleNotFoundError: No module named 'gql.transport.exceptions'
```

I've tried both python 3.6.5 & 3.7.0

**Comment by edgeee** [comment]
Hello. Thanks for reporting this. Would explain why the CI build failed. I will take a look

**Comment by r-musa** [comment]
@timigod  Fixed in [1.0.2](https://pypi.org/project/buycoins/1.0.2/)

You can try to install, but this time use (to avoid using local cache of the previous install you made):

` pip install --upgrade --no-cache-dir buycoins`

Let me know if it works for you, and I'll close the issue.

**Comment by smyja** [comment]
> @timigod Fixed in [1.0.2](https://pypi.org/project/buycoins/1.0.2/)
> 
> You can try to install, but this time use (to avoid using local cache of the previous install you made):
> 
> ` pip install --upgrade --no-cache-dir buycoins`
> 
> Let me know if it works for you, and I'll close the issue.

Its still showing the same error.

When I run that I see "gql 2.0.0 does not provide extra 'requests' python" along with requirement already satisfied for the other modules.

**Comment by ProsperChihimba** [comment]
I think the issue is in the version of gql that is been installed when installing the package.

So I uninstalled gql and installed gql version 3.

`pip uninstall gql`
`pip install gql==3.0.0a5`

you can read more here [https://stackoverflow.com/questions/67418484/azure-functions-module-errors-using-python](url)
